// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web.Microondas.Infrastructure.DatabaseContext;

#nullable disable

namespace Web.Microondas.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web.Microondas.Domain.Entities.HeatingProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasColumnType("nchar(1)")
                        .HasColumnName("character")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Food")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("food");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("instructions");

                    b.Property<bool>("IsPreset")
                        .HasColumnType("bit")
                        .HasColumnName("is_preset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("Power")
                        .HasColumnType("int")
                        .HasColumnName("power");

                    b.Property<int>("TimeInSeconds")
                        .HasColumnType("int")
                        .HasColumnName("time_in_seconds");

                    b.HasKey("Id");

                    b.HasIndex("Character")
                        .IsUnique();

                    b.ToTable("HeatingPrograms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Character = "*",
                            CreatedAt = new DateTime(2024, 2, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            Food = "Pipoca (de micro-ondas)",
                            Instructions = "Observar o barulho de estouros do milho, caso houver um intervalo de mais de 10 segundos entre um estouro e outro, interrompa o aquecimento.",
                            IsPreset = true,
                            Name = "Pipoca",
                            Power = 7,
                            TimeInSeconds = 180
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Character = "#",
                            CreatedAt = new DateTime(2024, 2, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            Food = "Leite",
                            Instructions = "Cuidado com aquecimento de líquidos, o choque térmico aliado ao movimento do recipiente pode causar fervura imediata causando risco de queimaduras.",
                            IsPreset = true,
                            Name = "Leite",
                            Power = 5,
                            TimeInSeconds = 300
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Character = "@",
                            CreatedAt = new DateTime(2024, 2, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            Food = "Carne em pedaço ou fatias",
                            Instructions = "Interrompa o processo na metade e vire o conteúdo com a parte de baixo para cima para o descongelamento uniforme.",
                            IsPreset = true,
                            Name = "Carnes de boi",
                            Power = 4,
                            TimeInSeconds = 840
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Character = "&",
                            CreatedAt = new DateTime(2024, 2, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            Food = "Frango (qualquer corte)",
                            Instructions = "Interrompa o processo na metade e vire o conteúdo com a parte de baixo para cima para o descongelamento uniforme.",
                            IsPreset = true,
                            Name = "Frango",
                            Power = 7,
                            TimeInSeconds = 480
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Character = "%",
                            CreatedAt = new DateTime(2024, 2, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            Food = "Feijão congelado",
                            Instructions = "Deixe o recipiente destampado e, em casos de plástico, cuidado ao retirar o recipiente pois o mesmo pode perder resistência em altas temperaturas.",
                            IsPreset = true,
                            Name = "Feijão",
                            Power = 9,
                            TimeInSeconds = 480
                        });
                });

            modelBuilder.Entity("Web.Microondas.Domain.Entities.Users", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("firstname");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("lastname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 2, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            Firstname = "Admin",
                            Lastname = "User",
                            Password = "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918",
                            Username = "ADM"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
